spring.application.name=psp

# R2DBC Configuration
spring.r2dbc.url=${R2DBC_URL:r2dbc:postgresql://localhost:5433/transaction_db}
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:postgres}

# Liquibase Configuration (Uses JDBC)
spring.liquibase.url=${JDBC_URL:jdbc:postgresql://localhost:5433/transaction_db}
spring.liquibase.user=${DB_USERNAME:postgres}
spring.liquibase.password=${DB_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
